### ISSUE TITLE
M2芯片不行

### ISSUE THREAD

**Issue by diaohancai** [SmallTeddy/EasyConnect#1]
M2芯片
版本：https://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg
提示“当前连接的vpn设备版本过低，不支持客户端下载”

**Comment by SmallTeddy** [comment]
> M2芯片 版本：https://download.sangfor.com.cn/download/product/sslvpn/pkg/mac_767/EasyConnect_7_6_7_4.dmg 提示“当前连接的vpn设备版本过低，不支持客户端下载”

sorry 我只尝试了M1芯片的

**Comment by SmallTeddy** [comment]
我看到有兄弟 M3 的芯片可以用
